name: publish
on:
  push:
    tags:
      - '*'
jobs:
  pre:
    name: pre
    runs-on: ubuntu-latest
    steps:
      - name: Stop process if the branch isn't the master
        # if: endsWith(github.ref, 'dfomin') == false
        run: |
          echo ${github.ref_name}
          echo ${GITHUB_REF}
  install-dependencies:
    name: install-dependencies
    needs: pre
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-$GITHUB_REF
  build:
    name: build
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: load cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-$GITHUB_REF
      - name: build from source
        run: yarn build:prod
  change-package:
    needs: install-dependencies
    name: change-package
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: run change package script
        run: |
          echo $GITHUB_REF
          ls -la
          cat package.json

        # TAG_VERSION=$GITHUB_REF node ./scripts/change-package.js
