name: publish
on:
  push:
    tags:
      - '*'
jobs:
  pre:
    name: pre
    runs-on: ubuntu-latest
    steps:
      - name: Stop process if the branch isn't the master
        if: endsWith(github.event.base_ref, 'dfomin') == false
        run: exit 1
      - name: Install dependencies
        run: yarn install
      - run: ls -la
      - name: Cache project
        uses: actions/cache@v3
        with:
          path: ./*
          key: project-${{ github.ref_name }}
  build:
    name: build
    needs: pre
    runs-on: ubuntu-latest
    steps:
      - name: Get project cache
        uses: actions/cache@v3
        with:
          path: .
          key: project-${{ github.ref_name }}
      - run: ls -la
      - name: Build from source
        run: yarn build:prod
      - name: Cache project
        uses: actions/cache@v3
        with:
          path: .
          key: project-${{ github.ref_name }}
  change-package:
    name: change-package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get project cache
        uses: actions/cache@v3
        with:
          path: .
          key: project-${{ github.ref_name }}
      - name: Run change package script
        run: TAG_VERSION=${GITHUB_REF#refs/tags/} node ./scripts/change-package.js
      - name: Cache project
        uses: actions/cache@v3
        with:
          path: .
          key: project-${{ github.ref_name }}
  publish-package:
    name: publish-package
    needs: change-package
    runs-on: ubuntu-latest
    steps:
      - name: Get project cache
        uses: actions/cache@v3
        with:
          path: .
          key: project-${{ github.ref_name }}
      - name: Publish into npm
        run: |
          ls -la
          cat package.json
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

        # yarn publish --access public