name: publish
on:
  push:
    tags:
      - '*'
jobs:
  .pre:
    name: .pre
    steps:
      - name: Stop process if branch isn't the master
        if: endsWith(github.ref, 'dfomin') == false
        run: exit -1
  install-dependencies:
    name: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - run: yarn install --frozen-lockfile
  build:
    name: build
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - run: yarn build:prod
  change-package:
    needs: install-dependencies
    name: change-package
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      # - run: TAG_VERSION=$GITHUB_REF node ./scripts/change-package.js
      - run: ls -la
      - run: cat package.json

