name: publish
on:
  push:
    tags:
      - '*'
jobs:
  pre:
    name: pre
    runs-on: ubuntu-latest
    steps:
      - name: Stop process if the branch isn't the master
        if: endsWith(github.event.base_ref, 'dfomin') == false
        run: exit 1
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Save project
        uses: actions/upload-artifact@v3
        with:
          name: project
          path: .
  build:
    name: build
    needs: pre
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/download-artifact@v3
        with:
          name: project
      - name: Build from source
        run: yarn build:prod
      - name: Save project
        uses: actions/upload-artifact@v3
        with:
          name: project
          path: .
  change-package:
    name: change-package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/download-artifact@v3
        with:
          name: project
      - name: Run change package script
        run: TAG_VERSION=${GITHUB_REF#refs/tags/} node ./scripts/change-package.js
      - name: Save project
        uses: actions/upload-artifact@v3
        with:
          name: project
          path: .
  publish-package:
    name: publish-package
    needs: change-package
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/download-artifact@v3
        with:
          name: project
      - name: Publish into npm
        run: |
          ls -la
          cat package.json
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

        # yarn publish --access public